cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - node_modules/

# test_e2e:
#   image: cypress/browsers:chrome67
#   stage: test
#   script:
#     - npm i
#     - npm run test:e2e -- --headless --record --key b2a22185-8eeb-4f0e-9b21-2d61f769d8c7
#   only:
#     - master

dev:build:
  image: node
  stage: build
  script:
    - yarn
    - yarn build:dev
  only:
    - dev
  tags:
    - eye-runner
  artifacts:
    expire_in: 1 week
    paths:
      - dist

dev:deploy:
  image: alpine:3.7
  stage: deploy
  script:
    # - echo "http://mirrors.aliyun.com/alpine/v3.7/main/" > /etc/apk/repositories
    # - apk add --no-cache rsync openssh
    # - mkdir -p ~/.ssh
    # - echo "$SSH_KEY_DEMO_PRIVATE" >> ~/.ssh/id_rsa
    # - echo "$SSH_KEY_DEMO_PUB" >> ~/.ssh/id_rsa.pub
    # - chmod 600 ~/.ssh/id_rsa
    # - chmod 600 ~/.ssh/id_rsa.pub
    # - echo -e "Host *\n\t StrictHostKeyChecking no \n\n" > ~/.ssh/config
    # - rsync -rav --delete ./dist/ "$SERVER_DEMO_HOST:$SERVER_DEMO_PATH"
    - echo "http://mirrors.aliyun.com/alpine/v3.7/main/" > /etc/apk/repositories
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY_DEV_PRIVATE" >> ~/.ssh/id_rsa
    - echo "$SSH_KEY_DEV_PUB" >> ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa.pub
    - echo -e "Host *\n\t StrictHostKeyChecking no \n\n" > ~/.ssh/config
    - rsync -rav --delete ./dist/ "$SERVER_DEV_HOST:$SERVER_DEV_PATH"
  only:
    - dev
  tags:
    - eye-runner

# prd:build:
#   image: tatsushid/tinycore-node
#   stage: build
#   script:
#     - npm i
#     - npm run build
#   only:
#     - master
#   tags:
#     - eye-runner
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - mark-system-web

# prd:deploy:
#   image: alpine:3.7
#   stage: deploy
#   script:
#     - echo "http://mirrors.aliyun.com/alpine/v3.7/main/" > /etc/apk/repositories
#     - apk add --no-cache rsync openssh
#     - mkdir -p ~/.ssh
#     - echo "$SSH_KEY_PRD_PRIVATE" >> ~/.ssh/id_rsa
#     - echo "$SSH_KEY_PRD_PUB" >> ~/.ssh/id_rsa.pub
#     - chmod 600 ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa.pub
#     - echo -e "Host *\n\t StrictHostKeyChecking no \n\n" > ~/.ssh/config
#     - rsync -rav --delete ./mark-system-web "$SERVER_PRD_HOST:$SERVER_PRD_PATH"
#   only:
#     - master
#   tags:
#     - ai-runner

test:build:
  image: node
  stage: build
  script:
    - yarn
    - yarn build:test
  only:
    - test
  tags:
    - ai-runner
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:deploy:
  image: alpine:3.7
  stage: deploy
  script:
    - echo "http://mirrors.aliyun.com/alpine/v3.7/main/" > /etc/apk/repositories
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY_TEST_PRIVATE" >> ~/.ssh/id_rsa
    - echo "$SSH_KEY_TEST_PUB" >> ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa.pub
    - echo -e "Host *\n\t StrictHostKeyChecking no \n\n" > ~/.ssh/config
    - rsync -rav --delete ./dist/ "$SERVER_TEST_HOST:$SERVER_TEST_SYSTEM_PATH"
  only:
    - test
  tags:
    - ai-runner
